//BLUE TOOTH DEVICE CONNECTED DETAILS
export const ALL_RECIVICED_DATA = "ALL_RECIVICED_DATA"
export const SET_CONNECTED_DEVICE = "SET_CONNECTED_DEVICE"
export const SET_SCANNED_DEVICES = "SET_SCANNED_DEVICES"
export const SET_ERROR = "SET_ERROR"
export const IS_CONNECTED = "IS_CONNECTED"
export const SET_TIMESTAMP = "SET_TIMESTAMP"
//leter add

// export const SET_USER = "SET_USER"
// export const IS_AUTHENTICATED = "IS_AUTHENTICATED"
